### ISSUE TITLE
Error using MongoDB on php 8.2

### ISSUE THREAD

**Issue by patrick-yi-82** [brefphp/aws-lambda-layers#77]
**Description:**

Error message output from Lambda

> Warning: PHP Startup: Unable to load dynamic library 'mongodb.so' (tried: /opt/bref/extensions/mongodb.so (libssl.so.1.1: cannot open shared object file: No such file or directory), /opt/bref/extensions/mongodb.so.so (/opt/bref/extensions/mongodb.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

**How to reproduce:**

```
functions:
  test:
    handler: public/test.php
    description: ''
    runtime: php-82
    layers:
      - ${bref-extra:mongodb-php-82}
```

In order for me to workaround this error on local docker, this is the command I added to Dockerfile

````
FROM bref/php-82-fpm-dev:2

# Fix "tried: /opt/bref/extensions/mongodb.so (libssl.so.1.1: cannot open shared object file: No such file or directory)" error
RUN yum -y install openssl11-libs.x86_64
````
